name       : draco
version    : 1.4.3
release    : 2
source     :
    - https://github.com/google/draco/archive/refs/tags/1.4.3.tar.gz : 02a620a7ff8388c57d6f6e0941eecc10d0c23ab47c45942fb52f64a6245c44f5
homepage   : https://google.github.io/draco/
license    : Apache-2.0
component  : multimedia.library
summary    : Draco 3D data compressor
description: |
    Draco is an open-source library for compressing and decompressing 3D geometric meshes and point clouds. It is intended to improve the storage and transmission of 3D graphics.
setup      : |
    %patch -p1 < $pkgfiles/soname-correction.patch
    %patch -p1 < $pkgfiles/strip-version-from-executables.patch
    %cmake_ninja \
        -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
        -DCMAKE_UNITY_BUILD=ON \
        -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -f $installdir/usr/lib*/*.a
