name       : draco
version    : 1.4.1
release    : 1
source     :
    - https://github.com/google/draco/archive/refs/tags/1.4.1.tar.gz : 83aa5637d36a835103a61f96af7ff04c6d6528e643909466595d51ee715417a9
homepage   : https://google.github.io/draco/
license    : Apache-2.0
component  : multimedia.library
summary    : Draco 3D data compressor
description: |
    Draco is an open-source library for compressing and decompressing 3D geometric meshes and point clouds. It is intended to improve the storage and transmission of 3D graphics.
setup      : |
    %patch -p1 < $pkgfiles/soname-correction.patch

    %cmake_ninja \
        -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
        -DCMAKE_UNITY_BUILD=ON \
        -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -f $installdir/usr/lib*/*.a
